GET http://localhost:3001/api/persons


###

DELETE http://localhost:3001/api/persons/3


####

POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Arto Hellas",
    "name": "Test",
    "number": "5318"
}

###

PUT http://localhost:3001/api/persons/627a291711ae353da7ada956
Content-Type: application/json

{
    "name": "Prova",
    "number": "0"
}

